# code taken from: https://github.com/Lightning-AI/litData/blob/main/.github/workflows/ci-checks.yml

name: General checks

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  check-typing:
    uses: Lightning-AI/utilities/.github/workflows/check-typing.yml@main
    with:
      actions-ref: main

  check-schema:
    uses: Lightning-AI/utilities/.github/workflows/check-schema.yml@main
    with:
      azure-dir: ""
