name: PyPI Release

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on: # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/release-pypi.yml"
  release:
    types: [published]

# based on https://github.com/pypa/gh-action-pypi-publish

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -U -q build twine
          pip list

      - name: Build package
        run: python -m build

      - name: Check package
        run: twine check dist/* --strict

      # We do this, since failures on test.pypi aren't that bad
      #  - name: Publish to Test PyPI
      #    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
      #    uses: pypa/gh-action-pypi-publish@v1.10.0
      #    with:
      #      user: __token__
      #      password: ${{ secrets.test_pypi_password }}
      #      repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
